---
# tasks file for devops_ansible-role-codedeploy-agent
- name: Install Ruby
  package:
    name: ruby
    state: present

- name: Fetch CodeDeploy Agent
  get_url:
    url: https://aws-codedeploy-{{ region }}.s3.{{ region }}.amazonaws.com/latest/install
    dest: /tmp/install

- name: Adding execution permission
  file:
    path: /tmp/install
    mode: u+x

- name: Install CodeDeploy Agent
  command: "/tmp/install auto"

- name: Disable service to avoid unexpected deploy
  systemd_service:
    name: codedeploy-agent
    enabled: false
    state: stopped
